[profile.default]
src = "src"
out = "out"
libs = ["lib"]
bytecode_hash = 'none'
#auto_detect_remappings = false
remappings = [
  'ds-test/=lib/forge-std/lib/ds-test/src/',
  'solady/=lib/solady/',
  'solarray/=lib/solarray/src/',
  'seaport-core/=lib/seaport-core/',
  'seaport-sol/=lib/seaport-sol/',
  'seaport-types/=lib/seaport-types/',
  'shipyard-core/=lib/shipyard-core/',
  'seadrop/=lib/seadrop/',
  'openzeppelin-contracts/=lib/shipyard-core/lib/openzeppelin-contracts',
  'ERC721A/=lib/seadrop/lib/ERC721A/contracts/'
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config